before_install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then sudo pip install unittest2; fi"
  - sudo pip install unittest-xml-reporting
  - sudo apt-get remove -y -o DPkg::Options::=--force-confold --purge libzmq3

script:
  - sudo python tests/runtests.py -vv

notifications:
  irc:
    channels: "irc.freenode.org#salt-devel"
    on_success: change
    on_failure: change
