---
name: 'Kitchen Vagrant (FreeBSD & OpenBSD)'
'on': ['push', 'pull_request']

env:
  KITCHEN_LOCAL_YAML: 'kitchen.vagrant.yml'

jobs:
  generate-actions-workflow:
    name: 'Generate The Actions Workflow'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
      - name: 'Set up Python 3.7'
        uses: 'actions/setup-python@v1'
        with:
          python-version: 3.7
      - name: 'Install Pre-Commit'
        run: |
          pip install -U pip
          pip install pre-commit
          pre-commit install
      - name: 'Generate Workflow Actions'
        run: |
          pre-commit run -av generate-actions-workflow
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    needs: 'generate-actions-workflow'
    container: 'koalaman/shellcheck-alpine:v0.6.0'
    steps:
      - uses: 'actions/checkout@v1'
      - name: 'ShellCheck'
        run: |
          shellcheck -s sh -f tty bootstrap-salt.sh
  test:
    runs-on: 'macos-10.15'
    timeout-minutes: 20
    needs: 'lint'
    strategy:
      fail-fast: false
      matrix:
        instance:
          # - py3-git-3000-freebsd-130
          # - py3-git-3000-freebsd-122
          # - py3-git-3000-openbsd-6
          - py3-git-3001-freebsd-130
          - py3-git-3001-freebsd-122
          # - py3-git-3001-openbsd-6
          - py3-git-3002-freebsd-130
          - py3-git-3002-freebsd-122
          # - py3-git-3002-openbsd-6
          - py3-git-3003-freebsd-130
          - py3-git-3003-freebsd-122
          # - py3-git-3003-openbsd-6
          - py3-git-master-freebsd-130
          - py3-git-master-freebsd-122
          # - py3-git-master-openbsd-6
          - latest-freebsd-130
          - latest-freebsd-122
          - latest-openbsd-6
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Set up Python 3.7'
        uses: 'actions/setup-python@v1'
        with:
          python-version: '3.7'
      - name: 'Install Python Dependencies'
        run: |
          pip install -U pip
          pip install -r tests/requirements.txt
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen test ${{ matrix.instance }}'
